# Generated by Django 5.0.2 on 2024-02-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin')], default='USER', max_length=100),
        ),
    ]
